### ISSUE TITLE
incorrect formatting on some specific patterns

### ISSUE THREAD

**Issue by vincent-fuchs** [fbaligand/vscode-logstash-editor#3] opened 2021-02-23 13:47 UTC
Hi,

formatting overall works well, but sometimes breaks.. I am not able to find the reason for now, but here's an example : 

```
 grok {
    patterns_dir => ["/usr/share/logstash/config/patterns/"]
    match => { "message" => "%{IP:[source][ip]} - - \[%{LOG_TIMESTAMP:timestamp}] \"%{WORD:method} %{RESOURCE:[url][path]}%{QUESTIONMARK_OR_NOT}%{QUERY_PARAMS:[url][query]} HTTP/%{NUMBER:[http][version]}\" %{NUMBER:[http][response][status_code]} %{NUMBER:[http][response][bytes]}" }
}
```

becomes after formatting : 

```
grok {
    patterns_dir => ["/usr/share/logstash/config/patterns/"]
    match => {
        "message" => "%{IP:[source][ip]} - - \[%{LOG_TIMESTAMP:timestamp}] \"% {
            WORD:method
                        }
% {
                RESOURCE:[url][path]
                    }
% {
                    QUESTIONMARK_OR_NOT
                }
% {
                        QUERY_PARAMS:[url][query]
            }
HTTP/% {
                            NUMBER:[http][version]
        }
\" %{NUMBER:[http][response][status_code]} %{NUMBER:[http][response][bytes]}"
    }
}
```

is there anything I should do in my config to avoid this ? 

I am using v0.4.0 in VSC 1.53.2

**Comment by vincent-fuchs** [comment] 2021-02-23 13:54
another example, not on a grok but on a simple if  : 

` else if [log][file][path] =~ /.*\/applogs\/service02\/my_app\/localhost_access_log\.\d{4}-\d{2}-\d{2}\.txt$/ {`

becomes 

```
else if [log][file][path] =~ /.*\/applogs\/service02\/my_app\/localhost_access_log\.\d {
    4
            }
-\d {
        2
        }
-\d {
            2
    }
\.txt$/ {
```

**Comment by fbaligand** [comment] 2021-02-23 15:51
Hi,

Thanks for this bug report. 

First, there is no configuration that could fix that. 

But you can do « local » formatting. 
I mean: you select (with mouse) the code that you want to format, and then you call « format » action. 
Doing so, you can choose the parts you want to format. 

That said, I will try to fix your formatting issue in next release. 

To give you some understanding, the problem is because editor gets confused with `{}` characters inside your string or regexp. It is because you have `\"` and `\/` that are not processed by editor as escaped characters.

**Comment by vincent-fuchs** [comment] 2021-02-23 19:35
Thanks for your quick confirmation - and thanks for the tip, maybe I can use it on parts of my 2000+ lines config file ! ;-)

**Comment by fbaligand** [comment] 2021-02-24 11:29
Hi,

I found the bug and fixed it.
So I'm happy to announce you that it will be part of next release!

**Comment by fbaligand** [comment] 2021-02-27 10:32
Hi @vincent-fuchs,

I'm pleased to announce you that Logstash Editor v0.5.0 is released and available on vscode marketplace!
So don't hesitate to update :)

This release includes a bug fix for this issue and some other enhancements:
https://github.com/fbaligand/vscode-logstash-editor/blob/master/CHANGELOG.md#050

**Comment by fbaligand** [comment] 2021-02-27 10:33
As issue is fixed, I close the issue.

**Closed as completed by fbaligand** 2021-02-27 10:33 UTC
Labels: bug

**Comment by vincent-fuchs** [comment] 2021-02-27 16:29
Thanks for the quick fix ! I updated and I confim it nows works fine !

**Comment by fbaligand** [comment] 2021-02-27 16:43
Great!

**Comment by vincent-fuchs** [comment] 2022-05-06 11:03
hi - this is the thread I mentioned to you during Devoxx - it was good meeting you in person, and I hope you found what you lost during the conference ! ;-)

**Comment by fbaligand** [comment] 2022-05-06 11:44
Hi @vincent-fuchs!

I didn't realized during Devoxx France that you opened an issue here!
I share the feeling that it was nice to meet you and discuss about Logstash editor extension!
I reassure you, people who takes by mistake my bag called me the same evening and I get back my bag (with all its content) few days later. I'm relieved!
